### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#1]
- As a user, I’m able to enter my personal information to create a new account in the Platform
- As a user, I’m able to reset my Password for login in my account
- As a user, I’m able to review the Privacy Policy and Terms and Conditions of the platform
- As a user, I want to be able to register my bank information to get paid when my products are - being sold

![image](https://user-images.githubusercontent.com/28816166/57780505-616bd500-76f6-11e9-82fa-e0f9a90f620b.png)

**Comment by alacret** [comment]
According to this: https://stripe.com/docs/ach#verifying

@wmata141 we need to collect:

- A check to see if it is Business or Personal Account
- Account holder's name
- Account number
- Routing number

**Comment by mayecham** [comment]
falta colocar los terminos y condiciones al momento de registrarme. registro listo.
