### ISSUE TITLE
Errores en diseño versus pantalla

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#129]
- [x] Pantalla de inventory no es como la del diseño 

![image](https://user-images.githubusercontent.com/28816166/65720760-edc8d400-e0a8-11e9-9f7a-5f2f81101370.png)

Diseño
![image](https://user-images.githubusercontent.com/28816166/65721266-02f23280-e0aa-11e9-8193-91344f787db7.png)
En caso de no tener nada la aditional fee (osea comision adicional) colocar 0%. 

- [x] Notificaciones. Quitar esta opcion 

- [x] Diseño de Sales tambien esta mal, Adjunto imagen de como debe verse
![image](https://user-images.githubusercontent.com/28816166/65722088-cd4e4900-e0ab-11e9-9838-03b88129d0be.png)

**Comment by wmata141** [comment]
Yo estoy asignando en commision el resultado expresado en dolares de aplicar la comision sobre el precio

**Comment by wmata141** [comment]
Listo

**Comment by mayecham** [comment]
@wmata141 que paso con esto: En caso de no tener nada la aditional fee (osea comision adicional) colocar 0%.
