### ISSUE TITLE
New Product 

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#13]
- As a user, I want to be able to have a Profile page where my pictures would be displayed, username, Full Name, and bio. 

- As a user, I want to be able to see other users Profile Page with the Post that they have created

![image](https://user-images.githubusercontent.com/28816166/58981968-77befb00-87a1-11e9-9cc4-9a964efcd9c6.png)

**Comment by wmata141** [comment]
Listo

**Comment by mayecham** [comment]
Hacerle mejoras a la vista, la imagen que quede en el recuadro sin espacios, hacer los circulos te talla y coleres mas pequeños y colocarle al color el color que corresponde.

**Comment by mayecham** [comment]
listo. Quizas podria sufrir cambios mas adelante por ahora esta ok
