### ISSUE TITLE
Sign Up Bug

### ISSUE THREAD

**Issue by Salalf01** [cobuildlab/bazl-admin#15]
- Revisar Sign Up 

- Type Error al introducir contraseña menor a 6 carateres por configuracion de Firebase.

![photo_2019-05-29_15-19-07](https://user-images.githubusercontent.com/31637622/58635892-02dd5400-82bd-11e9-9f37-4e54e650ee07.jpg)

**Comment by mayecham** [comment]
@wmata141  No puedo registrarme.

**Comment by mayecham** [comment]
listo
