### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#2]
- As a User with credentials, I want to provide my email and password and log into the platform
- As a User, I want to be able to recover my password if I want to do it

![image](https://user-images.githubusercontent.com/28816166/57780718-d5a67880-76f6-11e9-9f10-778925dad8e6.png)

![image](https://user-images.githubusercontent.com/28816166/57780759-e7881b80-76f6-11e9-98a0-5bc21e27f9a3.png)

**Comment by wmata141** [comment]
@alacret

**Comment by alacret** [comment]
@wmata141 check the kadem project to do this, basically:

-[ ] Create a form to request the recover password email, this is done with a Firebase SDK method and the user email
- [ ] Change the link on Firebase project to go to a RecoverPasswordView
- [ ] This view should capture the code form the URL, also should have a form to capture user email, and 2 fields for the new password. 
- [ ] Then using these 4 fields, validate the password, and use another Firebase SDK function to reset the password

**Comment by wmata141** [comment]
Okey okey

**Comment by mayecham** [comment]
Mejorar la interfaz de recuperar usuario. que el momento de cambiar la contraseña pida la contraseña nueva y al finalizar el proceso lleve a landing de inicio de sesion

**Comment by wmata141** [comment]
No entiendo como seria la mejora.  Asi lo hace: te regresa a la vista donde se introduce el usuario con la contraseña luego de enviada la nueva contraseña

**Comment by mayecham** [comment]
Asi es como deberia ser el flujo william. 
![image](https://user-images.githubusercontent.com/28816166/59612448-19701180-90eb-11e9-94ce-ddb199a7ca37.png)

![image](https://user-images.githubusercontent.com/28816166/59612499-2f7dd200-90eb-11e9-8f5c-355526317e60.png)

![image](https://user-images.githubusercontent.com/28816166/59612583-50debe00-90eb-11e9-9ca3-08a0d6982fc5.png)

![image](https://user-images.githubusercontent.com/28816166/59612608-5e944380-90eb-11e9-8bad-3e68792f4a7f.png)

Esta pantalla un boton de ir a home. para iniciar sesion.
