### ISSUE TITLE
 list of products to the platform with a CSV format file

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#25]
- Como usuario registrado en la plataforma web (Merchant) quiero poder subir una lista de productos a la plataforma con un archivo en formato CSV. (El formato del archivo será específico para la plataforma y esto no incluye la carga de archivos, las imágenes de los productos deben ser proporcionadas a través de un enlace URL).

- Después de cargar todos los detalles a través de la carga masiva. El Comerciante puede ir a la página de inventario para asignar imágenes al producto subiendo la Imagen a la plataforma.

**Comment by mayecham** [comment]
esto lo podemo comenzar a desarrollar tambien.

**Comment by mayecham** [comment]
@alacret como podria probar esto

**Comment by alacret** [comment]
@mayecham Tienes que preguntarle a @Salalf01
