### ISSUE TITLE
El detectar inactividad la sesion debe cerrarse 

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#39]
como usuario deseo que al tener 10 minutos de inactividad en la pagina, la sesion se cierre instantáneamente y me envie al login

**Comment by mayecham** [comment]
Se comienzan las actividads

**Comment by wmata141** [comment]
Se realizo como el proyecto kadem el cual tiene un check session para que el cliente verifique si la sesion se guarda o no

**Comment by mayecham** [comment]
Mejorar la vista en la opcion se ve el cuadro por un lado y las letras por otro revisa eso por favor. Y nunca cerro mi sesion a pesar de no tener eso activado 
![image](https://user-images.githubusercontent.com/28816166/60111291-af371c80-973b-11e9-8761-e6ef236f437e.png)
