### ISSUE TITLE
Perfil de Usuario

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#44]
Crear el carrusel de **Recently Tagged Publications** del perfil de Usuario. 
Configurar en el perfil las publicaciones recientes del usuario que inicia sesión.

**Comment by mayecham** [comment]
![image](https://user-images.githubusercontent.com/28816166/59522014-a91f8100-8e9b-11e9-9ee4-47508d8d899b.png)


Verifica la imagen y corrige please.

**Comment by wmata141** [comment]
Listo

**Comment by mayecham** [comment]
Listo
