### ISSUE TITLE
Mejorar y actualizar Home

### ISSUE THREAD

**Issue by mayecham** [cobuildlab/bazl-admin#65]
1. Hacer lo mas parecido al diseño la vista. 
![image](https://user-images.githubusercontent.com/28816166/59627479-513b8100-910c-11e9-8719-20a0e554398e.png)

2. Colocar los datos reales en cada opción. En este caso son 0 
![image](https://user-images.githubusercontent.com/28816166/59627606-a1b2de80-910c-11e9-8f8f-445493c75c7c.png)

3. Recent Sales 
No hay ventas por lo tanto debe estar vacio y un mensaje en ingles que diga: Usted aun no tienes ventas.

**Comment by mayecham** [comment]
En mi maquina sin tener ventas de una sale scroll, que no se ven bien. Creo que todo incluyendo los cuadros de las imagenes hay que hacerlos mas pequeños 

![image](https://user-images.githubusercontent.com/28816166/59712145-9c23ca00-91da-11e9-8225-fdf04b65b6ae.png)

**Comment by Salalf01** [comment]
@mayecham ok ya trabajé lo del botón de log out, update y modifique el diseño responsive un poco. lo de las imagenes con el escrito de recently publications y el que sale cuando no hay publicaciones decidi no modificarlo porque es algo donde william esta trabajando ya que todos esos estilos no estan en home, vienen de el componente donde el esta trabajando y eso puede generar conflicto al hacer merge, sin embargo le comente sobre esas correcciones y el me dijo que estaba hecho.

**Comment by mayecham** [comment]
Listo
